#!/bin/bash
set -e

docker-compose -f ./docker/docker-compose.yml up -d

echo "Waiting for Kuzzle to be up and running...."
./features/wait_for_kuzzle
echo "Running functional tests..."
./node_modules/cucumber/bin/cucumber-js -f json:report/cucumber-report.json



