#!/bin/bash

KUZZLE_HOST=localhost
KUZZLE_PORT=7512

RETRY=10

  curl -s $KUZZLE_HOST:$KUZZLE_PORT   > /dev/null
while [[ $? != 0 && $RETRY > 0 ]] ; do
  echo -e "[$RETRY] waiting for Kuzzle Server to be ready..."
  sleep 5
  ((RETRY--))
  curl -s $KUZZLE_HOST:$KUZZLE_PORT > /dev/null
done

if [[ $RETRY == 0 ]]
then
  exit 1
fi
